# This file was generated by GoReleaser. DO NOT EDIT.
class Yamlfmt < Formula
  desc "Formats yaml files."
  homepage "https://devopy.io/"
  url "https://github.com/devopyio/yamlfmt/releases/download/v1.0.4/yamlfmt_1.0.4_darwin_amd64.tar.gz"
  version "1.0.4"
  sha256 "32634b9b80f9635fa8293a0602616293601f6844dea50a5c62ce9baca7588be5"

  def install
    bin.install "yamlfmt"
  end

  def caveats; <<~EOS
    cat example.yaml | yamlfmt or yamlfmt -filename example.yaml
  EOS
  end
end
