# This file was generated by GoReleaser. DO NOT EDIT.
class Yamlfmt < Formula
  desc "Formats yaml files."
  homepage "https://devopy.io/"
  url "https://github.com/devopyio/yamlfmt/releases/download/v1.0.5/yamlfmt_1.0.5_Darwin_x86_64.tar.gz"
  version "1.0.5"
  sha256 "f4247cc08527334693358e4b0630e7c6ad23db8b420d4602e2ab6d845c2b1a49"

  def install
    bin.install "yamlfmt"
  end

  def caveats; <<~EOS
    cat example.yaml | yamlfmt or yamlfmt -filename example.yaml
  EOS
  end
end
