# This file was generated by GoReleaser. DO NOT EDIT.
class Yamlfmt < Formula
  desc "Formats yaml files."
  homepage "https://devopy.io/"
  url "https://github.com/devopyio/yamlfmt/releases/download/v1.0.3/yamlfmt_1.0.3_darwin_amd64.tar.gz"
  version "1.0.3"
  sha256 "357732d7941868314c6d04d34be6379eb771d8eb705281fe7393b54aaff3dac6"

  def install
    bin.install "yamlfmt"
  end

  def caveats; <<~EOS
    cat example.yaml | yamlfmt or yamlfmt -filename example.yaml
  EOS
  end
end
